language: python
python:
- 3.8
- 3.7
- 3.6
- 3.5
- 2.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: ilionesso
  password:
    secure: YHUvaSG7UMRh8GHTd+rjdc0yOBRZoIiyTbEVcHA5DJFNzWZ3WJro7SUGo5SrU4YAezkRQ9jkVEZQlcDteMFjtgfZd3CqluNhNvNruTCKcBFjv5h16+V6FXpLruWk17l7XpQht0eON+2PdaVLprKt8x2MYRHsh3i7oN4d0J0nlheDyfv364lIIZpgT8aAaW4Z2+efikpqc5Tc9zYIYTkMdKY6Ur31T8dEtKI27qbhWZulIfCNTYxbC+E0M6XoPubgOT1jTbRgL9mMsecaJ8kZDyldRBa7AFZV9JrAvgnrVqGEDnri2PqFo2nuBzxh3NvDPD668W5bZtdbBfdeGxAqguyc4q8nrkUvbzRw/MqxdTO/wTmpOTQ8y90ycPz+dIit3yjFJ82WTDP7aSCLVdjXwmeb5SgpeF079Mntvwa8a56o4wzM+Xi+r+8WhPpHzX3Tb7+5R7t90iCn6aOzeTHA0xQg0hTPzrG/KPTzDRU5GQ2EJ4p76l2V5sr0ucarAYXhZCKMstzn0G2QidohSl4SYF3Brnq+SsK89VX84i3MkCK64wItJZv1RC33OrIzapaeecZZkugGEROBoix3ncEhBxuEwSrgL8ti7YtRzB1tMetWOD9cFXfA6R4rBUJCZq0Bs+eofa/vPuseAMz9AUeosr/v8G7EFo5hxDoHlpE/rA4=
  on:
    tags: true
    repo: Ilionesso/cookiecutter_exersise
    python: 3.8
